export const UPDATE_USER_ID = 'UPDATE_USER_ID';
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const UPDATE_QUESTION_ID = 'UPDATE_QUESTION_ID';

export const UPDATE_QUESTION_DATA = 'UPDATE_QUESTION_DATA';
export const UPDATE_USER_SCORE = 'UPDATE_USER_SCORE';
export const UPDATE_TRUE_NUMBER = 'UPDATE_TRUE_NUMBER';
export const UPDATE_FALSE_NUMBER = 'UPDATE_FALSE_NUMBER';

export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
